redis1:
  image: redis:latest
  ports:
    - "6379"
  command: redis-server --save ""

redis2:
  image: redis:latest
  ports:
    - "6379"
  command: redis-server --save ""

statsd:
  image: hopsoft/graphite-statsd
  ports:
    - "80"
    - "8125/udp"
  environment:
    VIRTUAL_HOST: pandapush-graphite.docker
    VIRTUAL_PORT: 80

dynamo:
  build: docker/dynamo
  command: -dbPath /var/lib/dynamodb
  volumes:
    - "./docker/data/dynamo:/var/lib/dynamodb"
  ports:
    - "8000"
  environment:
    VIRTUAL_HOST: pandapush-dynamo.docker
    VIRTUAL_PORT: 8000

webpack:
  build: .
  command: bash -c "
    node_modules/.bin/webpack --watch --devtool inline-source-map --config ui/webpack.config.js &
    node_modules/.bin/webpack --watch --devtool inline-source-map --config client/webpack.config.js"
  working_dir: /usr/src/app
  volumes:
    - "./:/usr/src/app"
  environment:
    NODE_ENV: development

web:
  build: .
  command: ./node_modules/.bin/nodemon --watch app/ app/app.js
  volumes:
    - ".:/usr/src/app"
  links:
    - redis1
    - redis2
    - statsd
  environment:
    VIRTUAL_HOST: pandapush.docker
    VIRTUAL_PORT: 3000
    ADMIN_USERNAME: admin
    ADMIN_PASSWORD: password
    REDIS_URL_ENV_VARS: REDIS1_URL,REDIS2_URL
    REDIS1_URL: tcp://redis1:6379
    REDIS2_URL: tcp://redis2:6379
    DATA_STORE: FILE
    NODE_ENV: development
    STATSD_HOST: statsd
    STATSD_PORT: 8125